sudo: required

services:
  - docker

before_install:
  - docker build -t jaydp17/jenkins-slave-nodejs:7.10 7.10

script:
  - docker run --user jenkins jaydp17/jenkins-slave-nodejs:7.10 bash -c "yarn global add grunt-cli"
  - docker run --user jenkins jaydp17/jenkins-slave-nodejs:7.10 bash -c "npm i -g eslint"
